[[inputs.nginx]]
  urls = ["http://nginx-container/nginx_status"]
  response_timeout = "5s"

[[inputs.cpu]]
  percpu = true

[[inputs.disk]]

[[inputs.diskio]]

[[inputs.net]]
  # Remove deprecated param
  # ignore_protocol_stats = false

[[inputs.mem]]

[[inputs.system]]

# Prometheus output plugin

[[outputs.prometheus_client]]
  listen = ":9273"
