FROM certbot/certbot:latest

# Установка необходимых пакетов
RUN apk update && \
    apk add --no-cache \
    curl \
    bash \
    openssl \
    docker-cli

# Создаем директории для логов
RUN mkdir -p /var/log/certbot && \
    chmod 755 /var/log/certbot

# Копируем только скрипт получения сертификатов
COPY .docker/scripts/get-certificates.sh /scripts/get-certificates.sh
RUN chmod +x /scripts/*.sh

ENTRYPOINT ["/scripts/get-certificates.sh"] 
